
spring.datasource.url=jdbc:mysql://localhost:3306/alert_engine_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1726
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest




spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-6p5syw5vn131xu8k.us.auth0.com/


spring.security.oauth2.resourceserver.jwt.audience=https://api.precios-indumentariaSaaS.com

cors.allowed-origins=${CORS_ORIGINS:http://localhost:3000,http://localhost:8080}

# Static files
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/frontend/**

app.telegram.bot-token=7805759839:AAGXyWVqr7kdahUxKUK8wSslIwrAORdjxHw
app.telegram.chat-id=5581094202

# Auth0 Client Credentials
auth0.client-id=M25mEZO5kThSSUQfKy7bYcWskCt3NIMu
auth0.client-secret=y2Q68sgvDzM0EPOv9j8YwsfxEqpd2w80e_lRAGuOp6sbvQPsdQ1m4v3EckduYhpL