### Guardar un sitio nuevo
POST http://localhost:8080/api/sites
Content-Type: application/json

{
  "url": "https://es.wikipedia.org/wiki/Java_(lenguaje_de_programaci%C3%B3n)",
  "name": "Monitor Wikipedia Java",
  "cssSelector": "#firstHeading",
  "checkIntervalMinutes": 120,
  "active": true
}


### 2. Obtener todos los sitios (GET)
GET http://localhost:8080/api/sites


### 3 Prueba de integración
GET http://localhost:8080/api/snapshots/site/1


## 4 Prueba de usuario registrando nuevo sitio
###
POST http://localhost:8080/api/sites
Content-Type: application/json

{
  "name": "Precio Bitcoin - CoinMarketCap",
  "url": "https://coinmarketcap.com/currencies/bitcoin/",
  "cssSelector": ".main-price",
  "active": true,
  "checkIntervalMinutes": 5
}

### Preuba de sitio web creado con link suministrado por nosotros
POST http://localhost:8080/api/products/with-link
Content-Type: application/json

{
  "name": "Zapatilla Urbana Blanca",
  "brand": "Adidas",
  "category": "Calzado",
  "gender": "Unisex",
  "storeName": "Tienda Oficial Adidas",
  "url": "https://www.dexter.com.ar/zapatillas-adidas-court-hombre/ADIE0927_11.5_1.html",
  "priceSelector": ".price-active",
  "installmentsSelector": ".installments-info",
  "freeShippingThreshold": 0.0,
  "isActive": true
}



